# encoding: utf-8

module Language
  Languages = {
    'Arabic' => 'ar',
    'Bulgarian' => 'bg',
    'Catalan' => 'ca',
    'Chinese, PRC' => 'zhCN',
    'Chinese, traditional characters, non-PRC locales' => 'zh',
    'Croatian' => 'hr',
    'Czech' => 'cs',
    'Danish' => 'da',
    'Dutch' => 'nl',
    'English' => 'en',
    'Finnish' => 'fi',
    'French' => 'fr',
    'German' => 'de',
    'Greek' => 'el',
    'Hebrew' => 'he',
    'Hindi' => 'hi',
    'Hungarian' => 'hu',
    'Indonesian' => 'id',
    'Italian' => 'it',
    'Japanese' => 'ja',
    'Korean' => 'ko',
    'Latvian' => 'lv',
    'Lithuanian' => 'lt',
    'Norwegian bokmål' => 'nb',
    'Polish' => 'pl',
    'Portuguese' => 'pt',
    'Portuguese, Brazil' => 'ptBR',
    'Romanian' => 'ro',
    'Russian' => 'ru',
    'Serbian' => 'sr',
    'Slovak' => 'sk',
    'Slovenian' => 'sl',
    'Spanish' => 'es',
    'Swedish' => 'sv',
    'Tagalog' => 'tl',
    'Thai' => 'th',
    'Turkish' => 'tr',
    'Ukrainian' => 'uk',
    'Vietnamese'=>'vi'
  }
end
