#!/bin/bash

ps -C mongod >/dev/null
if [ $? -eq 0 ]; then
    echo "Error: mongod appears to already be running"
    exit
fi

mkdir -p ~/.mongo/db

mongod --nojournal --auth --smallfiles -nssize 4 --fork --dbpath ~/.mongo/db --logpath /home/darshan/.mongo/log

sleep 0.1
