#!/bin/bash

if [ ! -e run/pid ]
then
    echo "$0: run/pid does not exist, so I can't stop your app"
    exit 1
fi

pid=`cat run/pid`

kill $pid >run/log

if [ "$?" -ne 0 ]
then
    echo "$0: could not kill $pid"
    exit 2
fi

rm run/pid
rm /tmp/ath.sock
